name: Build ClanGen Modding Tool Nightly

# build nightly
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: 'macos-latest'
            os-target: 'osx-x64'
          - runner: 'windows-latest'
            os-target: 'win-x64'
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Build project
        run: dotnet publish ClanGenModTool.sln -r ${{ matrix.os-target }} -c Release -o bin/${{ matrix.os-target }}

      - name: Bundle project
        run: tar -czvf ClanGenModTool-${{ matrix.os-target }}.tar.gz bin/${{ matrix.os-target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClanGenModTool-${{ matrix.os-target }}
          path: bin/ClanGenModTool-${{ matrix.os-target }}.tar.gz